# Generated by Django 5.1.2 on 2025-06-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='bank_slip',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_bank_slips/'),
        ),
    ]
