# Generated by Django 5.1.2 on 2025-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
