# Generated by Django 5.1.2 on 2025-06-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_token_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Repairing', 'Repairing'), ('Return', 'Return'), ('Received', 'Received'), ('OK', 'OK')], max_length=10),
        ),
    ]
